---
spring:
  config:
    activate:
      on-profile: 'local, !api-docs'
springdoc:
  api-docs:
    path: /api-docs
    groups:
      enable: true
    resolve-schema-properties: true
  swagger-ui:
    path: /swagger
    enabled: true
    disable-swagger-default-uri : true
  cache:
    diabled: true
  http:
    encoding:
      charset: 'UTF-8'
      enabled: true
      force: true
      force-response : true
---
spring:
  application:
    name: oss
  thymeleaf:
    mode: HTML
    cache: false
  cloud:
    config:
      enabled: true
      uri: http://localhost:9296
    zookeeper:
      config:
        enabled: false
  datasource:
    username: admin
    password: rhkdgo3762
    url: jdbc:log4jdbc:mysql://database-goms.cdqwi0uis6zq.ap-northeast-2.rds.amazonaws.com:3306/gomsdb?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.jdbc.batch_size: 25
      hibernate.jdbc.fatch_size: 150
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.criteria.literal_handling_mode: BIND
    hibenate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

      database: mysql
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          use_sql_comments: true
      hibernate:
        ddl-auto: none
  mvc:
    static-path-pattern: /static/** 
  main:
    allow-circular-references: true
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  messages:
    basename: i18n/messages
  output:
    ansi:
      console-available: true
  servlet:
    multipart:
      max-file-size: 50MB
      max_request-size: 50MB	
server:
  port: 8003
  servlet:
    context-path: '/'

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:log4j2.xml
  level:
    dev.developery.mybatis.mapper: debug
goms:
  clientapp:
     name: 'OSS'

#elasticsearch:
#  host: localhost
#  port: 9200
#  indecies:
#    studentsIndexName: students
#    testIndexName: tests